//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioDent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AOdontologico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AOdontologico()
        {
            this.Expediente = new HashSet<Expediente>();
        }
    
        public int Identificador { get; set; }
        [Display(Name = "Tratamiento Previo")]
        public string TratamientoPrevio { get; set; }
        public Nullable<int> Extracciones { get; set; }
        public Nullable<int> Profilaxis { get; set; }
        public Nullable<int> Endodoncia { get; set; }
        [Display(Name = "Prótesis")]
        public Nullable<int> Protesis { get; set; }
        [Display(Name = "Amalgama")]
        public Nullable<int> Amaigama { get; set; }
        public Nullable<int> Resinas { get; set; }
        [Display(Name = "Ortopedia Maxiliar")]
        public Nullable<int> OrtopediaMaxiliar { get; set; }
        public Nullable<int> Ortodoncia { get; set; }
        [Display(Name = "Alergico Anestésico")]
        public Nullable<int> AlegicoAnestico { get; set; }
        [Display(Name = "Última visita al Dentista")]
        public Nullable<System.DateTime> FechaUltimaVisitaDentisata { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expediente> Expediente { get; set; }
    }
}
