//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioDent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Consulta
    {
        public int Identificador { get; set; }
        [Display(Name = "Fecha de la Cita")]
        public Nullable<System.DateTime> FechaCita { get; set; }
        [Display(Name = "Hora de la Cita")]
        public Nullable<System.TimeSpan> HoraCita { get; set; }
        [Display(Name = "Nombre del Paciente")]
        public Nullable<int> Paciente { get; set; }
        [Display(Name = "Nombre del LE:")]
        public Nullable<int> Medico { get; set; }
        [Display(Name = "Motivo de Cita")]
        public string Motivo { get; set; }
    
        public virtual Medico Medico1 { get; set; }
        public virtual Paciente Paciente1 { get; set; }
    }
}
