//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioDent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EIntraOral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EIntraOral()
        {
            this.Expediente = new HashSet<Expediente>();
        }
    
        public int Identificador { get; set; }
        public string Labios { get; set; }
        public string PaladarDuro { get; set; }
        public string PaladarBlando { get; set; }
        public string Farinje { get; set; }
        public string PisoBoca { get; set; }
        public string GlandulasSalivales { get; set; }
        public string TamanioFormaDiente { get; set; }
        public string ProcesoAlveolares { get; set; }
        public string EstadoGeneral { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expediente> Expediente { get; set; }
    }
}
