//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioDent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expediente
    {
        public int Identificador { get; set; }
        public Nullable<System.DateTime> FechaExpediente { get; set; }
        public Nullable<int> Paciente { get; set; }
        public Nullable<int> Patologico { get; set; }
        public Nullable<int> NoPatologico { get; set; }
        public Nullable<int> Odontologico { get; set; }
        public Nullable<int> Hereditario { get; set; }
        public Nullable<int> ExtraOral { get; set; }
        public Nullable<int> IntraOral { get; set; }
        public Nullable<int> ATM { get; set; }
        public Nullable<int> Odontograma { get; set; }
    
        public virtual AHereditario AHereditario { get; set; }
        public virtual ANoPatologico ANoPatologico { get; set; }
        public virtual AOdontologico AOdontologico { get; set; }
        public virtual APatologico APatologico { get; set; }
        public virtual EATM EATM { get; set; }
        public virtual EExtraOral EExtraOral { get; set; }
        public virtual EIntraOral EIntraOral { get; set; }
        public virtual Odontograma Odontograma1 { get; set; }
        public virtual Paciente Paciente1 { get; set; }
    }
}
