//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioDent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odontograma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odontograma()
        {
            this.Expediente = new HashSet<Expediente>();
        }
    
        public int Identificador { get; set; }
        public Nullable<int> Diente { get; set; }
        public string Pronostico { get; set; }
        public string Diagnostivo { get; set; }
        public string Tratamiento { get; set; }
        public Nullable<int> Paciente { get; set; }
    
        public virtual Diente Diente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expediente> Expediente { get; set; }
        public virtual Paciente Paciente1 { get; set; }
    }
}
