//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioDent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Consulta = new HashSet<Consulta>();
            this.Expediente = new HashSet<Expediente>();
            this.Odontograma = new HashSet<Odontograma>();
        }
    
        public int Identificador { get; set; }
        public string NombreCompleto
        {
            get { return Nombre + ApellidoPaterno + ApellidoMaterno; }
        }
        public string Nombre { get; set; }
       
        public string ApellidoPaterno { get; set; }
       
        public string ApellidoMaterno { get; set; }
        [Display(Name = "Seudónimo")]
        public string Seudominio { get; set; }

        [Display(Name ="Lugar de Nacimiento")]
        public string LugarNacimiento { get; set; }
        [Display(Name ="Fecha de Nacimiento")]
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Escolaridad { get; set; }
        public string Tutor { get; set; }
        [Display(Name ="Estado Civil")]
        public string EstadoCivil { get; set; }
        public string Domicilio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> Consulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expediente> Expediente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odontograma> Odontograma { get; set; }
    }
}
